all:
	 g++ \
	 Entity.cpp \
	 main.cpp \
	 Camera.cpp \
	 Skybox.cpp \
	 BlockInterpolator.cpp \
	 LightSource.cpp \
	 Smoke.cpp \
	 BRepMaterial.cpp \
	 Application.cpp \
	 Boid.cpp \
	 BoundingSphere.cpp \
	 Vector3.cpp \
	 PoseAttribute.cpp \
	 Rain.cpp \
	 BRep.cpp \
	 ColoredEntity.cpp \
	 TexturedEntity.cpp \
	 Keyframing.cpp \
	 PolynomInterpolator.cpp \
	 Pose.cpp \
	 BRepGroup.cpp \
	 LinearInterpolator.cpp \
	 BoundingAABB.cpp \
	 VectorAttribute.cpp \
	 Character.cpp \
	 PivotedBRep.cpp \
	 FloatAttribute.cpp \
	 Pivot.cpp \
	 Particle.cpp \
	 IntAttribute.cpp \
	 BRepFace.cpp \
	 BoundingVolume.cpp \
	 Planet.cpp \
	 CharacterAction.cpp \
	 RigidBody.cpp \
	 Water.cpp \
	 IronTrail.cpp \
	 Wind.cpp \
	 MageParticle.cpp \
	 Grass.cpp \
	 Timer.cpp \
	 GlowCometa.cpp \
-o AniV7.o -lGL -lGLU -lglut -O3

test: all
	./AniV7.o
