all:
	g++ \
	main.cpp \
	Actor.cpp \
	Animator.cpp \
	Application.cpp \
	Camera.cpp \
	Entity.cpp \
	Fence.cpp \
	House.cpp \
	Interpolator.cpp \
	LinearInterpolator.cpp \
	Object.cpp \
	PoseAttr.cpp \
	PrimitiveGL.cpp \
	Robot.cpp \
	Tree.cpp \
	Vector3.cpp \
	WavefrontObject.cpp \
	-o ANI.o \
	-lGL -lGLU -lglut -O3
