all:
	g++ main_CPP.cpp \
	Actor.cpp \
	Animator.cpp \
	Application.cpp \
	Aquarium.cpp \
	AttrVector3.cpp \
	BlockingInterpolator.cpp \
	Camera.cpp \
	Cat.cpp \
	Chair.cpp \
	Desk.cpp \
	Entity.cpp \
	Fence.cpp \
	Fish.cpp \
	Helix.cpp \
	House.cpp \
	Interpolator.cpp \
	Joint.cpp \
	Light.cpp \
	LinearInterpolator.cpp \
	Matrix.cpp \
	Object.cpp \
	Planet.cpp \
	PolynomInterpolator.cpp \
	PoseAttr.cpp \
	PrimitiveGL.cpp \
	Robot.cpp \
	Table.cpp \
	Tree.cpp \
	Vector3.cpp \
	-o AniV6.o \
	-lGL -lGLU -lglut -O3
