all:
	g++ main.cpp \
 	Application.cpp \
	Camera.cpp \
	Entity.cpp \
	Fence.cpp \
	House.cpp \
	Object.cpp \
	PrimitiveGL.cpp \
	Tree.cpp \
	Vector3.cpp \
	-o  AniEngine.o \
	-lGL -lGLU -lglut -O3 -Wall
