all:
	 g++ \
	 BRepMaterial.cpp \
	 Character.cpp \
	 CharacterAction.cpp \
	 Pivot.cpp \
	 Planet.cpp \
	 FloatAttribute.cpp \
	 VectorAttribute.cpp \
	 Entity.cpp \
	 Camera.cpp \
	 IntAttribute.cpp \
	 BRepGroup.cpp \
	 LinearInterpolator.cpp \
	 BRepFace.cpp \
	 ColoredEntity.cpp \
	 LightSource.cpp \
	 main.cpp \
	 BRep.cpp \
	 Application.cpp \
	 PoseAttribute.cpp \
	 PivotedBRep.cpp \
	 TexturedEntity.cpp \
	 Pose.cpp \
	 Keyframing.cpp \
	 Vector3.cpp \
-o AniV7.o -lGL -lGLU -lglut -O3
